// ──────────────────────────────────────────────────────────────────────────
//  Country name → flag-icons code (ISO 3166-1 alpha-2, lowercase; home nations
//  use GB subdivision codes). Covers every plausible 2026 World Cup nation so
//  flags "just work" as teams get added. Add a line if a country is missing.
// ──────────────────────────────────────────────────────────────────────────

const CODES: Record<string, string> = {
  // hosts + CONCACAF
  usa: "us",
  "united states": "us",
  mexico: "mx",
  canada: "ca",
  "costa rica": "cr",
  jamaica: "jm",
  panama: "pa",
  honduras: "hn",
  "el salvador": "sv",
  haiti: "ht",
  curacao: "cw",
  curaçao: "cw",
  // south america
  argentina: "ar",
  brazil: "br",
  uruguay: "uy",
  colombia: "co",
  ecuador: "ec",
  paraguay: "py",
  chile: "cl",
  peru: "pe",
  bolivia: "bo",
  venezuela: "ve",
  // europe
  spain: "es",
  france: "fr",
  england: "gb-eng",
  scotland: "gb-sct",
  wales: "gb-wls",
  "northern ireland": "gb-nir",
  portugal: "pt",
  germany: "de",
  netherlands: "nl",
  italy: "it",
  belgium: "be",
  croatia: "hr",
  denmark: "dk",
  switzerland: "ch",
  austria: "at",
  poland: "pl",
  serbia: "rs",
  ukraine: "ua",
  norway: "no",
  sweden: "se",
  czechia: "cz",
  "czech republic": "cz",
  turkey: "tr",
  türkiye: "tr",
  turkiye: "tr",
  hungary: "hu",
  greece: "gr",
  romania: "ro",
  slovenia: "si",
  slovakia: "sk",
  albania: "al",
  // africa
  morocco: "ma",
  senegal: "sn",
  nigeria: "ng",
  egypt: "eg",
  ghana: "gh",
  cameroon: "cm",
  "ivory coast": "ci",
  "cote d'ivoire": "ci",
  "côte d'ivoire": "ci",
  algeria: "dz",
  tunisia: "tn",
  "south africa": "za",
  "cape verde": "cv",
  "cabo verde": "cv",
  "dr congo": "cd",
  "democratic republic of the congo": "cd",
  mali: "ml",
  // asia + oceania
  japan: "jp",
  "south korea": "kr",
  korea: "kr",
  "korea republic": "kr",
  iran: "ir",
  australia: "au",
  "saudi arabia": "sa",
  qatar: "qa",
  iraq: "iq",
  uzbekistan: "uz",
  jordan: "jo",
  uae: "ae",
  "united arab emirates": "ae",
  "new zealand": "nz",
};

/** Returns the flag-icons country code for a name, or null if unknown. */
export function countryCode(name: string): string | null {
  return CODES[name.trim().toLowerCase()] ?? null;
}
